# Generated by Django 5.0.4 on 2026-02-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='media')),
                ('tavsifi', models.TextField()),
                ('chegirma', models.IntegerField()),
                ('narxi', models.IntegerField()),
                ('arzon_narx', models.BooleanField(default=False)),
                ('xaqiqiy', models.BooleanField(default=False)),
            ],
        ),
    ]
