# Generated by Django 5.0.4 on 2026-02-18 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0002_mahsulot'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='turi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='uzum.mahsulot_turi'),
        ),
    ]
