# Generated by Django 5.0.4 on 2026-02-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0003_mahsulot_turi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='rangi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
