# Generated by Django 5.0.4 on 2026-02-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0004_mahsulot_rangi'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='ikkinchi_rasm',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='qoshimcha_ikkinchi_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='qoshimcha_tortinchi_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='qoshimcha_uchunchi_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='qoshimchi_birinchi_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
