# Generated by Django 5.0.4 on 2026-02-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0005_mahsulot_ikkinchi_rasm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot_soni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='soni',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mahsulotlar', to='uzum.mahsulot_soni'),
        ),
    ]
