# Generated by Django 5.0.4 on 2026-03-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzum', '0006_mahsulot_soni_mahsulot_soni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('tavsif_uchun', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
